### ISSUE TITLE
elasticsearch 开启 xpack

### ISSUE THREAD

**Issue by dacheng-gao** [successgo/blog#45]
## 生成证书

```shell
$ elasticsearch-certutil ca
$ elasticsearch-certutil cert --ca elastic-stack-ca.p12
```

将生成的2份证书文件移入 `config` 目录

## 修改配置文件 $ESHOME/config/elasticsearch.yml

```yaml
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
```

> $ESHOME 指代 elasticsearch 安装目录

## 设置 es 用户密码

```shell
$ $ESHOME/bin/elasticsearch-setup-passwords interactive
```
