### ISSUE TITLE
logstash 简单配置

### ISSUE THREAD

**Issue by dacheng-gao** [successgo/blog#46]
## 主配置文件

配置文件位置 `$LOGSTASH_HOME/config/logstash.yml`

```yaml
http.host: "0.0.0.0"
http.port: 9600
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: qwer1234
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.monitoring.collection.interval: 10s
```

## pipeline example

```
input {
  rabbitmq {
    durable => true
    exclusive => false
    passive => false
    codec => "json"
    host => "localhost"
    port => 5672
    user => "USER"
    password => "PASS"
    prefetch_count => 5
    ssl => false
    vhost => "/"
    threads => 5
    exchange => "EXCHANGE"
    key => "KEY"
    queue => "QUEUE"
    type => "TYPE"
  }
}

output {
  elasticsearch { 
    hosts => ["localhost:9200"]
    index => "%{type}-%{+YYYYMMdd}"
    document_id => "%{id}"
    user => "USER"
    password => "PASS"
  }
}
```
